feat: hw2
Learning-Now/2021-Java-Study pull request #11
Opened 2021-01-08 08:34 UTC by dustndus8

2021-01-11 04:02 UTC, Livenow14 requested changes
세세한 부부들이 조금 부족한것들이 있음. 추가바랍니다.

2021-01-11 04:02 UTC, Livenow14 commented on 2주차과제/2주차과제_코드실습.txt
> +```
live template 만드는 법을 더 해보는 것도 좋을듯 
또한, 더 많은 live template이 있으니 확인바람.

2021-01-11 04:02 UTC, Livenow14 commented on 2주차과제/2주차과제_코드실습.txt
> +***
전체라인 자동 리펙토링 기능 확인바람

2021-01-11 04:02 UTC, Livenow14 commented on 2주차과제/2주차과제_코드실습.txt
> +```
클래스 조회 부분도 추가 바람

2021-01-13 04:57 UTC, dustndus8 commented
2주차 완료

2021-01-13 04:57 UTC, closed without merging