[4주차] LDH
Learning-Now/2021-Java-Study pull request #25
Opened 2021-01-20 05:36 UTC by DongLee99

2021-01-25 14:54 UTC, Livenow14 approved these changes
조금 더 본인의 말로 풀어봐도 좋을듯

2021-01-25 14:54 UTC, Livenow14 commented on 4week/4week.md
> +코딩의 관점에서 본다면 클래스가 객체를 만들기위한 틀, 도구이기에 객체지향을 클래스 라고 착각할수가 있다. 객체지향의 주인공은 클래스가 아니라 객체 이다. 이 객체를 분류 하기 위한 것이 클래스 이다. 따라서 코드를 담는 클래스의 관점이 아닌 메시지를 주고 받는 객체의 관점으로 애플리케이션을 바라 보아야 한다.
goood

2021-01-25 14:54 UTC, Livenow14 commented on 4week/4week.md
> +* 애플리케이션의 기능은 좀 더 작은 책임으로 분할되며 책임은 적절한 역할을 수행할수 있는 객체에 의해 수행된다. ( 객체 지향 설계 = > 적절한 객체에 적절한 책임을 할당함으로 부터 시작)
책임은 역할을 수행할 수 있는 객체에 의해 수행 

객체가 먼저일까요,  책임이 먼저일까요?

2021-01-25 14:54 UTC, Livenow14 commented on 4week/4week.md
> +(그냥 내 생각인데 이는 자바에서 코드를 짤때 메서드를 호출해 직접 상태를 변형 시키거나 다른 객체의 상태를 변형 시키는 것, 이때 변환 시킬 객체를 아는 것 등을 의미하는것 같다)
메서드를 호출한다라는 말이 입에 붙지않게 조심!
여기서의 말은 뭔가 다른객체의 상태를 알아야한다는 전제가 깔려있는 것 같아요. 

저는 하는 것과 아는 것을 메소드의 개념으로 생각하는 것이 아닌, 하는 것(수신된 책임을  수행하는 것, 맡은 역할에서 해야할 행동) 아는 것 (어떠한 책임을 필요로 하는지 아는 것(관련된 객체에 대해 알아야함), 나의 상태에 대한 정보  )라는, 넓은 의미에서 생각했어요

2021-01-25 14:54 UTC, Livenow14 commented on 4week/4week.md
> +    * 너무 추상적인 메시지는 의도가 변형될수있으므로 구체적이여한다.
예제가 있으면 조금더 좋을거같아요

2021-01-25 14:54 UTC, Livenow14 commented on 4week/4week.md
> +    * 역할은 대체 가능성을 의미한다.
객체지향의 어떠한 성질 덕분에 이러한 가능성을 의미하게 되는 걸까요?

2021-01-25 14:54 UTC, Livenow14 commented on 4week/4week.md
> +
조금더 본인의 말로 다듬어도 좋을듯

2021-01-25 14:54 UTC, Livenow14 commented on 4week/4week.md
> +_그렇다면 계속 str에 재할당을 한다면 객체가 생성된채로 낭비가 된다는 것인데 이는 어떻게 처리하는게 옳은 방법일까?_
GC의 대상이 되는거죠!

2021-01-25 14:54 UTC, Livenow14 commented on 4week/4week.md
> +    * String Builder 는 String 과 다르게 mutable 하기 때문에 변경을 하더라고 새로운 객체를 만들지 않고 기존 할당된 값을 수정 한다. 즉 문자열 변경과 연산을 하는 경우 기존의 버퍼 크기를 늘리거나 줄이면서 유연한 동작이 가능하게 된다.
알고리즘 문제풀이 에서 String Builder가 빠른이유!

2021-01-25 15:03 UTC, Livenow14 reviewed
기초 피드백.
수업시간에 조금더 다뤄볼 것이 많음.

2021-01-25 15:03 UTC, Livenow14 commented on 4week/4week.md
> +---
Collection.unmodified 라는 옵션도 살펴보실

2021-01-25 15:03 UTC, Livenow14 commented on 4week/4week.md
> +
switch문 -> switch 연산자가 된것이 아닌,
swtich문 + switch 연산자가 된 것 입니다. 
정리가 조금더 필요할듯!

2021-01-29 06:28 UTC, Livenow14 commented
Caludator 클래스에
시작, 입력, 출력, 계산, 숫자 저장등의 책임을 다 지니고 잇네요.

2021-01-29 06:29 UTC, Livenow14 commented
그리고 쓰지않을 Hello.java이런 것들은 가독성에서 오히려 방해가 되니 삭제 바랍니다.

2021-01-29 14:31 UTC, PandaHun requested changes
조금 더 설명이 필요한 코드라 생각이 필요할 것 같습니다 :)

2021-01-29 14:31 UTC, PandaHun commented on 4week/bringjava/src/main/java/Hello.java
> +    public static void main(String [] args){
뭐하는 파일이에요?

2021-01-29 14:31 UTC, PandaHun commented on 4week/bringjava/src/main/java/Calculator.java
> +
공백제거

2021-01-29 14:31 UTC, PandaHun commented on 4week/bringjava/src/main/java/Calculator.java
> +class Cal {
public? private? default?

2021-01-29 14:31 UTC, PandaHun commented on 4week/bringjava/src/main/java/Calculator.java
> +    public BigDecimal add(BigDecimal first, String second) {
float, long, double은 지원하지 않나요?

2021-01-29 14:31 UTC, PandaHun commented on 4week/bringjava/src/main/java/Calculator.java
> +    public BigDecimal add(BigDecimal first, String second) {
세개 넣으면 돌아가나요?

2021-01-29 14:31 UTC, PandaHun commented on 4week/bringjava/src/main/java/Calculator.java
> +        } catch (Exception e) {
어떤 exception인가요?
예를 들어 InvalidArgumentException?, MathaticalException? 등 명시적으로 예측 가능한 Exception을 남겨주세요

2021-01-29 14:31 UTC, PandaHun commented on 4week/bringjava/src/main/java/Calculator.java
> +            return split(str);
이해가 쉽게 안가는거 같은데 설명 부탁드려요

2021-01-29 14:31 UTC, PandaHun commented on 4week/bringjava/src/main/java/Calculator.java
> +            BigDecimal result = new BigDecimal(str[0]);
0번 인덱스 데이터가 의미하는게 뭐에요?

2021-01-29 14:31 UTC, PandaHun commented on 4week/bringjava/src/main/java/Calculator.java
> +            if (str.length % 2 == 0) {
왜 잘못된거에요?

2021-01-29 14:31 UTC, PandaHun commented on 4week/bringjava/src/main/java/Calculator.java
> +            for (int i = 0; i < str.length - 2; i += 2) {
숫자가 네자리라면 동작이 들어갈까요?

2021-02-21 12:59 UTC, closed without merging