[4주차] BLINK-ONCE
Learning-Now/2021-Java-Study pull request #27
Opened 2021-01-24 12:38 UTC by BLINK-ONCE

2021-01-30 13:54 UTC, Livenow14 approved these changes
자바 기초부분 정리 잘했네요! 
객체 지향 부분에선 예제가 조금더 추가 되면 좋을 것 같아요.

2021-01-30 13:54 UTC, Livenow14 commented on 4weeks/1.practical training.md
> +
좋은 의견.

2021-01-30 13:54 UTC, Livenow14 commented on 4weeks/1.practical training.md
> +- 객체가 충분히 추상적이면서 미니멀리즘을 따르는 인터페이스를 가지게 하고 싶다면 메시지가 객체를 선택하게 하자.
메시지가 제일 중요하다! 라는 말의 정리본이라 볼 수 있겠네요

2021-01-30 13:54 UTC, Livenow14 commented on 4weeks/1.practical training.md
> +
GOOOD

2021-01-30 13:54 UTC, Livenow14 commented on 4weeks/1.practical training.md
> +
근데 GET, SET을 다여는건 좋진 않아요. 상황에 따라 하는 것이 좋습니다.

2021-01-30 13:54 UTC, Livenow14 commented on 4weeks/1.practical training.md
> +
살짝 부족한 설명.
예제가 더 필요할거 같아요.

2021-01-30 13:54 UTC, Livenow14 commented on 4weeks/2.java basics.md
> +위처럼 메소드를 람다 표현식으로 쓰면 클래스를 작성하고 객체를 생성하지 않아도 메소드를 사용할 수 있다.
람다 표현식이 나온 배경, 언제부터 사용가능한지도 정리해볼만 한듯!

2021-01-30 18:46 UTC, BLINK-ONCE commented on 4weeks/1.practical training.md
> +
넵

2021-02-01 03:42 UTC, PandaHun requested changes

2021-02-01 03:42 UTC, PandaHun commented on 4weeks/stringCalc/src/main/java/Calculator.java
> +        input.inputFormula();
패키지의 메인만 보면 공식을 입력 받는게 끝인데
계산은 어떤 객체가 책임을 지고 있는지 와닿지 않습니다.

2021-02-01 03:42 UTC, PandaHun commented on 4weeks/stringCalc/src/main/java/Input.java
> +        for (int i = 1; i < arrayFormula.length; i += 2) {// 피연산자 중 숫자가 아닌 것이 있을 경우
홀수 index를 의미한 것 같은데
저는 그 홀수 index가 무엇을 의미하는지 모르겠습니다

2021-02-01 03:42 UTC, PandaHun commented on 4weeks/stringCalc/src/main/java/Input.java
> +            if (isElementInt(arrayFormula[i - 1]) == false || isElementInt(arrayFormula[i + 1]) == false) {
이미 boolean을 return 하는애가 false 인지 검증을 해야한다면
그 상황이 true인 경우로 메소드를 만들고 네이밍을 하는게 더 맞지 않을까요?

2021-02-01 03:42 UTC, PandaHun commented on 4weeks/stringCalc/src/main/java/Input.java
> +        if (isComputable) {// 피연산자가 들어갈 부분에 모두 들어갔다면 연산 시작
computable 하지 않다면?
사용자는 입력을 했지만 아무 것도 안되는 것처럼 보이는데 의도된게 맞나요?

2021-02-01 03:42 UTC, PandaHun commented on 4weeks/stringCalc/src/main/java/Input.java
> +            System.out.println("입력된 값이 숫자가 아닙니다.");
입력된 어떤 수가 숫자가 아닐까요?

2021-02-01 03:42 UTC, PandaHun commented on 4weeks/stringCalc/src/main/java/Input.java
> +    public void inputFormula() throws IOException {
검증과 계산의 책임을 한 곳에서 하는 것 같아 보이네요

2021-02-21 13:00 UTC, closed without merging