[4주차] ejy
Learning-Now/2021-Java-Study pull request #28
Opened 2021-01-24 15:19 UTC by jeongyuneo

2021-01-29 07:44 UTC, Livenow14 reviewed
vo, 객체 역할 책임 협력은  자바개발자라면 평생 알고있어야할 지식입니다.

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/VO(Value Object).md
> +VO의 핵심 역할은 **equals()**와 **hashcode()**를 오버라이딩 하는 것이다. 즉, VO 내부에 선언된 속성(필드)의 모든 값들이 VO 객체마다 값이 같아야 같은 객체라고 판별한다.
핵심 역할 앞에 조금더 설명(정의라던지, 언제 쓰는지?)이 있으면 좋을거같아요~~

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/VO(Value Object).md
> +생성자가 주입될 때 값의 유효성을 확인해야 한다. 유효하지 않으면 의미있는 에러를 표출한다. 이는 객체의 인스턴스에 더이상 if가 없음을 의미한다. **모든 유효성 검사는 생성 시간**에 이루어진다.
이는 프로그래밍 과제에서 확인해볼 수 있겠네요.

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/객체 지향-역할, 책임, 협력.md
> +객체를 스스로 생각하고 스스로 결정하는 현실 세계의 생명체에 비유하는 것은 상태와 행위를 **'캡슐화'**하는 소프트웨어 객체의 **'자율성'**을 설명하는 데 효과적이다. 현실 세계의 사람들이 암묵적인 약속과 명시적인 계약을 기반으로 목표를 달성해 나가는 과정은 **'메시지'**를 주고받으며 공동의 목표를 달성하기 위해 **'협력'**하는 객체들의 관계
여기서 제일 중요한 말은 메시지!

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/객체 지향-역할, 책임, 협력.md
> +- 객체는 시스템의 행위를 구현하기 위해 다른 객체와 협력한다. 각 객체는 협력 내에서 정해진 역할을 수행하며 역할을 관련된 책임의 집합이다.
협력 -> 역할 -> 책임 
객체들간의 협력이 우선시 되야하고 역할과 책임은 **메시지**를 통해 정리될 수 있습니다.

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/객체 지향-역할, 책임, 협력.md
> +- 역할은 개체 가능성을 의미한다.
대체~

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/객체 지향-역할, 책임, 협력.md
> +역할은 협력 내에서 다른 객체로 대체할 수 있음을 나타내는 일종의 표식이다. 협력 안에서 역할은 "이 자리는 해당 역할을 수행할 수 있는 어떤 객체라도 대신할 수 있습니다."라고 말하는 것과 같다.
다형성을 풀어쓴 말

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/객체 지향-역할, 책임, 협력.md
> +역할의 대체 가능성은 행위 호환성을 의미하고, 행위 호환성은 동일한 책임의 수행을 의미한다.
행위라는 말이 어려울수 있으니 속성, 행위는 상태, 행동으로 쭉 표현해도 좋을듯!

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/객체 지향-역할, 책임, 협력.md
> +책임이란 객체가 어떤 행동을 하라고 다른 객체로부터 요청을 수신했을 때 요청을 처리하기 위해 객체가 수행하는 행동이다.
즉. 메시지를 수신받았을 때 그 메시지의 요청을 처리하기위해 수행하는 행동

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/객체 지향-역할, 책임, 협력.md
> +    - 자신이 유도하거나 계산할 수 있는 것에 대해 아는 것
calculator에서 하는 것과 아는것을 한번 분리해보는게 어때요?

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/객체 지향-역할, 책임, 협력.md
> +    - 자신이 유도하거나 계산할 수 있는 것에 대해 아는 것
그게 예제가 되겠네요.

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/객체 지향-역할, 책임, 협력.md
> +
매우 중요

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/객체 지향-역할, 책임, 협력.md
> +- 데이터를 보이지 않고 외부와 상호작용을 할 때는 메소드를 이용하여 통신을 한다. 보통 라이브러리로 만들어서 업그레이드해 사용할 수 있다.
다형성은 메시지 수신자의 종류를 캡슐화한다~

2021-01-29 07:44 UTC, Livenow14 commented on 4주차/객체 지향-역할, 책임, 협력.md
> +
어떻게~ 가 아닌 무엇을~을 먼저 생각하는것

2021-01-29 14:39 UTC, PandaHun requested changes
조금 더 고민 부탁드려요:)

2021-01-29 14:39 UTC, PandaHun commented on 4주차/프로그래밍과제1/src/main/java/Calculator.java
> +    public int add(int a, int b) {
float, double, long에 대한 지원은 안되나요?

2021-01-29 14:39 UTC, PandaHun commented on 4주차/프로그래밍과제1/src/main/java/Operator.java
> +    public static void executeCalc(String[] arr) throws Exception {
이게 외부로 노출 될 필요있을까요?

2021-01-29 14:39 UTC, PandaHun commented on 4주차/프로그래밍과제1/src/main/java/Operator.java
> +        String arr[] = bf.readLine().split(" ");
쉼표로 구분되는 계산기라면 동작을 정상적으로 할 수 있을 까요?

2021-01-29 14:39 UTC, PandaHun commented on 4주차/프로그래밍과제1/src/main/java/Operator.java
> +            sum = Integer.parseInt(arr[0]);
0번 인덱스 데이터가 의미하는게 무엇인가요?

2021-01-29 14:39 UTC, PandaHun commented on 4주차/프로그래밍과제1/src/main/java/Operator.java
> +            sum = Integer.parseInt(arr[0]);
arr는 뭔가요?

2021-01-29 14:39 UTC, PandaHun commented on 4주차/프로그래밍과제1/src/main/java/Operator.java
> +        } catch (Exception e) {
무슨 exception이든 다 여기서 걸리겠네요?

2021-01-29 14:39 UTC, PandaHun commented on 4주차/프로그래밍과제1/src/main/java/Operator.java
> +        for (int i = 1; i < arr.length; i = i + 2) {
+2는 어떤 기준인가요?

2021-01-29 14:39 UTC, PandaHun commented on 4주차/프로그래밍과제1/src/main/java/Operator.java
> +                num = Integer.parseInt(arr[i + 1]);
무슨 예외 처리에요?

2021-01-29 17:22 UTC, jeongyuneo commented on 4주차/객체 지향-역할, 책임, 협력.md
> +- 역할은 개체 가능성을 의미한다.
수정완료

2021-02-01 07:22 UTC, jeongyuneo commented on 4주차/VO(Value Object).md
> +VO의 핵심 역할은 **equals()**와 **hashcode()**를 오버라이딩 하는 것이다. 즉, VO 내부에 선언된 속성(필드)의 모든 값들이 VO 객체마다 값이 같아야 같은 객체라고 판별한다.
수정 완료

2021-02-02 08:02 UTC, jeongyuneo commented on 4주차/객체 지향-역할, 책임, 협력.md
> +객체를 스스로 생각하고 스스로 결정하는 현실 세계의 생명체에 비유하는 것은 상태와 행위를 **'캡슐화'**하는 소프트웨어 객체의 **'자율성'**을 설명하는 데 효과적이다. 현실 세계의 사람들이 암묵적인 약속과 명시적인 계약을 기반으로 목표를 달성해 나가는 과정은 **'메시지'**를 주고받으며 공동의 목표를 달성하기 위해 **'협력'**하는 객체들의 관계
확인

2021-02-02 08:04 UTC, jeongyuneo commented on 4주차/객체 지향-역할, 책임, 협력.md
> +- 객체는 시스템의 행위를 구현하기 위해 다른 객체와 협력한다. 각 객체는 협력 내에서 정해진 역할을 수행하며 역할을 관련된 책임의 집합이다.
확인

2021-02-02 08:05 UTC, jeongyuneo commented on 4주차/객체 지향-역할, 책임, 협력.md
> +책임이란 객체가 어떤 행동을 하라고 다른 객체로부터 요청을 수신했을 때 요청을 처리하기 위해 객체가 수행하는 행동이다.
수정 완료

2021-02-02 08:16 UTC, jeongyuneo commented on 4주차/객체 지향-역할, 책임, 협력.md
> +
확인

2021-02-02 08:20 UTC, jeongyuneo commented on 4주차/객체 지향-역할, 책임, 협력.md
> +- 데이터를 보이지 않고 외부와 상호작용을 할 때는 메소드를 이용하여 통신을 한다. 보통 라이브러리로 만들어서 업그레이드해 사용할 수 있다.
수정 완료

2021-02-02 08:33 UTC, jeongyuneo commented on 4주차/객체 지향-역할, 책임, 협력.md
> +
확인

2021-02-21 12:39 UTC, closed without merging