[4주차] ysy
Learning-Now/2021-Java-Study pull request #29
Opened 2021-01-25 01:34 UTC by dustndus8

2021-01-31 11:31 UTC, Livenow14 requested changes
역할, 책임, 협력, 메시지 부분의 설명이 조금 부족한거같아요! 스터디 이후 더 추가하는게 좋을거 같아요!

2021-01-31 11:31 UTC, Livenow14 commented on 4주차과제/자바기초.md
> +
동일하지 않을땐 무엇을 사용할까요?

2021-01-31 11:31 UTC, Livenow14 commented on 4주차과제/자바기초.md
> +
예제가 있으면 더 좋을듯!

2021-01-31 11:31 UTC, Livenow14 commented on 4주차과제/자바기초.md
> +
람다 함수란 -> 익명 함수를 지칭하는 -> 익명 함수란 이름이 없는이라고 설명이 되어있는데 쉬운 예제 하나정도는 좋겠다는 말임.

2021-01-31 11:31 UTC, Livenow14 commented on 4주차과제/자바코드실습.md
> +
내가??

2021-01-31 11:31 UTC, Livenow14 commented on 4주차과제/자바코드실습.md
> +```
예제가 잘못됏어요.
생성자를 추가바랍니다.

2021-01-31 11:31 UTC, Livenow14 commented on 4주차과제/자바코드실습.md
> +
메시지에 대한 설명은 어디있나요?

2021-01-31 14:52 UTC, dustndus8 commented on 4주차과제/자바기초.md
> +
익명함수 예제 추가했습니다!

2021-01-31 14:55 UTC, dustndus8 commented on 4주차과제/자바코드실습.md
> +
해당 내용 삭제 했습니다!

2021-01-31 14:56 UTC, dustndus8 commented on 4주차과제/자바기초.md
> +
형변환을 사용해야한다고 생각합니다!!

2021-02-01 03:49 UTC, PandaHun requested changes
참고 hackday java code convention
https://naver.github.io/hackday-conventions-java/

2021-02-01 03:49 UTC, PandaHun commented on 4주차과제/프로그래밍과제1/Calculator.java
> +public class Calculator{
주석이 필요하지 않은 메소드와 변수명으로 이해 가능한 코드를 작성하는 것이 좋습니다.

2021-02-01 03:49 UTC, PandaHun commented on 4주차과제/프로그래밍과제1/Calculator.java
> +        String[] str_result;    // 문자열 자른 후의 배열
code convention

2021-02-01 03:49 UTC, PandaHun commented on 4주차과제/프로그래밍과제1/util/sum.java
> +public class sum {
code convention

2021-02-01 03:49 UTC, PandaHun commented on 4주차과제/프로그래밍과제1/util/sum.java
> +    public void InputWrong(String in) {
code convention

2021-02-01 03:49 UTC, PandaHun commented on 4주차과제/프로그래밍과제1/util/sum.java
> +    public void InputWrong(String in) {
메소드 이름만 보면 "입력이 잘못됐구나" 라고 생각 드는데
동작은 입력에 대한 검증을 수행하고 있습니다.
이에 맞는 네이밍을 해주는 게 어떨까요?

2021-02-01 03:49 UTC, PandaHun commented on 4주차과제/프로그래밍과제1/util/sum.java
> +            if (sps[i + 1].equals("+")) {
i+1번째가 의미하는게 무엇인가요?

2021-02-01 03:49 UTC, PandaHun commented on 4주차과제/프로그래밍과제1/util/sum.java
> +                sum = add(sum, to_Int(sps[i + 2]));
i+2번째가 의미하는 것 또한 무엇일까요?

2021-02-02 03:29 UTC, dustndus8 commented on 4주차과제/자바코드실습.md
> +```
예제 수정했습니다!

2021-02-02 03:34 UTC, dustndus8 commented on 4주차과제/자바코드실습.md
> +
메시지에 대한 설명 추가했습니다

2021-02-02 03:41 UTC, dustndus8 commented on 4주차과제/프로그래밍과제1/util/sum.java
> +    public void InputWrong(String in) {
네이밍 수정 완료했습니다!

2021-02-02 05:51 UTC, dustndus8 commented on 4주차과제/프로그래밍과제1/Calculator.java
> +        String[] str_result;    // 문자열 자른 후의 배열
수정 완료했습니다

2021-02-02 05:53 UTC, dustndus8 commented on 4주차과제/프로그래밍과제1/util/sum.java
> +    public void InputWrong(String in) {
네이밍 수정 완료했습니다!

2021-02-07 04:52 UTC, dustndus8 commented on 4주차과제/프로그래밍과제1/Calculator.java
> +public class Calculator{
바꿀 것이 많아 새 프로젝트를 만들어 수정 후 5주차 과제에 올렸습니다!

2021-02-07 04:52 UTC, dustndus8 commented on 4주차과제/프로그래밍과제1/util/sum.java
> +public class sum {
5주차 과제에 수정 했습니다!

2021-02-07 04:53 UTC, dustndus8 commented on 4주차과제/프로그래밍과제1/util/sum.java
> +            if (sps[i + 1].equals("+")) {
공백에 따라 구분해주기때문에 배열의 홀수번째 인덱스는 연산자인 것을 뜻했습니다. 5주차 과제에 올린 것에 주석 추가했습니다!

2021-02-07 04:54 UTC, dustndus8 commented on 4주차과제/프로그래밍과제1/util/sum.java
> +                sum = add(sum, to_Int(sps[i + 2]));
i+2번째는 마찬가지로 숫자를 의미합니다! 이 또한 주석 추가 했습니다!

2021-02-07 04:54 UTC, closed without merging