Jeongyun
Learning-Now/2021-Java-Study pull request #3
Opened 2020-12-28 14:22 UTC by jeongyuneo

2020-12-28 15:01 UTC, Livenow14 requested changes
마크다운 형식도 공부해서 올려주세요.

2020-12-28 15:01 UTC, Livenow14 commented on 1주차/git 명령어
> +### 작업 폴더(Working Directory) -> 인덱스(Staging Area) -> 저장소(Head-Repository)
가독성 부분에서 어떻게 개선할 수 있을지 생각바람.

2020-12-30 12:48 UTC, Livenow14 approved these changes
전반적으로 좋으나, 한번 생각해봐야할 부분들이 조금 있음.

2020-12-30 12:48 UTC, Livenow14 commented on 1주차/git 명령어.md
> +```
이렇게 ```를 쓰는 경우, 명령어를 포현할 때 리눅스 기준 **$**, 윈도우 기준 **>**을 표현함.

2020-12-30 12:48 UTC, Livenow14 commented on 1주차/마크다운 작성법.md
> +사이즈를 조절 하려면 ```<img width="" height=""></img>```를 이용한다.
이미지를 표현하는 방법도 좋지만, 링크를 표현하는 방법도 생각해봤으면 좋겠음.

2020-12-31 01:32 UTC, jeongyuneo commented on 1주차/마크다운 작성법.md
> +사이즈를 조절 하려면 ```<img width="" height=""></img>```를 이용한다.
2-6. 링크 작성법 외에 이미지에 링크 거는 방법 말하는건가요?

2020-12-31 01:32 UTC, jeongyuneo commented on 1주차/git 명령어.md
> +```
수정하겠습니다.

2020-12-31 02:13 UTC, Livenow14 commented on 1주차/마크다운 작성법.md
> +사이즈를 조절 하려면 ```<img width="" height=""></img>```를 이용한다.
이미지를 클릭시 바로 이미지 다운로드 링크로 가는 것이 아닌, 레포지토리 폴더 내의 이미지로 가게 할 수 있습니다. 
예로 ,https://github.com/Livenow14/spring-boot-blog의 이미지를 클릭하면, image폴더로 이동하게 됩니다.

2021-01-01 12:55 UTC, jeongyuneo commented on 1주차/git 명령어
> +### 작업 폴더(Working Directory) -> 인덱스(Staging Area) -> 저장소(Head-Repository)
수정완료

2021-01-01 12:56 UTC, jeongyuneo commented on 1주차/마크다운 작성법.md
> +사이즈를 조절 하려면 ```<img width="" height=""></img>```를 이용한다.
수정완료

2021-01-07 08:13 UTC, closed without merging