[4주차] nyj
Learning-Now/2021-Java-Study pull request #30
Opened 2021-01-30 20:48 UTC by dbswl067

2021-01-31 11:51 UTC, Livenow14 reviewed
예제만 조금 더 추가하면 완벽할듯

2021-01-31 11:51 UTC, Livenow14 commented on 4주차 과제/자바 기초.md
> +
예제 만드는 습관 good !

2021-01-31 11:51 UTC, Livenow14 commented on 4주차 과제/자바 기초.md
> +함수를 따로 만들지 않고 코드 한 줄에 함수를 써서 그것을 호출하는 방식을 말한다.
어디서 많이 쓰는지도 공부해보는게 좋을듯?

2021-01-31 11:51 UTC, Livenow14 commented on 4주차 과제/자바 코드 실습.md
> +객체지향을 생각하면 가장 먼저 "클래스"가 떠오른다. 클래스는 객체를 여러 개 만들어내는 설계도(또는 틀)이다. 객체지향이라는 소설의 주인공은 "클래스"가 아니라 "객체"이다. "클래스"의 생산물이 "객체"가 아니라, "객체"를 분류하기 위해 등장한 것이 "클래스"이다. 객체지향 설계에서 중요한 것은 어떤 클래스가 필요한가가 아니라 어떤 객체들이 어떤 메
중요 문장!

2021-01-31 11:51 UTC, Livenow14 commented on 4주차 과제/자바 코드 실습.md
> +
캡슐화에 대한 설명도 추가되면 좋을거 같아요

2021-01-31 11:51 UTC, Livenow14 commented on 4주차 과제/자바 코드 실습.md
> +
요것도 예제가 조금 아쉽네요

2021-01-31 11:51 UTC, Livenow14 commented on 4주차 과제/자바 코드 실습.md
> +
예제 한번 추가해봐요!

2021-01-31 11:51 UTC, Livenow14 commented on 4주차 과제/자바 코드 실습.md
> +
이것도 예제를 추가하면, vo와 차이점을 확인해볼 수 있을듯

2021-02-01 04:06 UTC, PandaHun requested changes

2021-02-01 04:06 UTC, PandaHun commented on 4주차 과제/java_study/src/main/java/Calc.java
> +            System.out.println("숫자가 아닌 문자가 입력되었습니다.");
어떤 문자가 아니였는지 사용자가 알 수 없겠네요?

2021-02-01 04:06 UTC, PandaHun commented on 4주차 과제/java_study/src/main/java/Calc.java
> +            CheckNum1 = isStringDouble(str[op - 1]);
변수명1, 변수명2는 좋은 코드가 아닙니다

2021-02-01 04:06 UTC, PandaHun commented on 4주차 과제/java_study/src/main/java/Calc.java
> +    private double add(double first_value, double second_value){
code convention

2021-02-01 04:06 UTC, PandaHun commented on 4주차 과제/java_study/src/main/java/Calc.java
> +        for(op = 1; op < str.length; op += 2){
for문에서 사용하는 문자열을 굳이 static 변수로 선언한 이유가 있나요?

2021-02-21 12:59 UTC, closed without merging