[5주차]LDH
Learning-Now/2021-Java-Study pull request #33
Opened 2021-02-02 06:36 UTC by DongLee99

2021-02-07 06:51 UTC, Livenow14 reviewed
code convention을 의식적으로 생각해도 좋을거같아요

2021-02-07 06:51 UTC, Livenow14 commented on 5week/5week.md
> +
가독성 측면에서 switch를 잘안쓴다고 합니다.

2021-02-07 06:51 UTC, Livenow14 commented on 5week/5week.md
> +** 반복문 예제(for, while, do-while) **
메소드를 잘 분리하고,  책임을 잘 분리하면 성능을 높일 수 있어요

2021-02-07 06:51 UTC, Livenow14 commented on 5week/LinkedList/src/main/java/Main.java
> +    }
code convention

2021-02-07 06:51 UTC, Livenow14 commented on 5week/LinkedList/src/main/java/Main.java
> +        } else {
setter가 꼭 필요할까요?? 
set이 아닌 add 라는 식의 네이밍도 괜찮을 거 같아요

2021-02-07 06:51 UTC, Livenow14 commented on 5week/calculator/document/calculator.md
> +
### 
```suggestion
# 기능 정리
- [ ] 넘버, 연산자 객체 모델링
```
이런씩으로 사용해도 괜찮을듯!

2021-02-07 06:51 UTC, Livenow14 commented on 5week/calculator/src/main/java/Application.java
> +    }
이해안가는 선언부입니다. 
new 는인스턴스화를 한다는 것인데, 
이렇게 인스턴스화 시에는 인스턴스 변수에 할당을 하고, 이후 동작을 진행해도 좋을듯 합니다.

2021-02-07 06:51 UTC, Livenow14 commented on 5week/calculator/src/main/java/Domain/Number.java
> +
convention

2021-02-07 06:51 UTC, Livenow14 commented on 5week/calculator/src/main/java/Domain/Number.java
> +    }
if문 안에, 또 BigDecimal을 인스턴스화 해야하는 이유가 있나요 ?

2021-02-07 06:51 UTC, Livenow14 commented on 5week/calculator/src/main/java/Service/Cal.java
> +}
하나의 메소드에서 4가지 5가지 일을 하고잇네요, 변경해도 괜찮을거같아요

2021-02-07 06:51 UTC, Livenow14 commented on 5week/stack/src/main/java/Main.java
> +}
이건 무슨 클래스인지..?!

2021-02-07 08:05 UTC, PandaHun requested changes
메소드, 클래스명 함축 주의
git 제대로 처리하기
계속된 객체 생성

위의 3가지를 생각해보세요

2021-02-07 08:05 UTC, PandaHun commented on README.md
> +<<<<<<< HEAD
git 처리

2021-02-07 08:05 UTC, PandaHun commented on 5week/calculator/src/main/java/Service/StringSplit.java
> +public class StringSplit {
결국 CalStart는 분할된 String 배열을 갖고 동작하는데,
한번만 변환해줄거라면 굳이 getArr로 호출 해야 하는지 생각이 필요할 것 같습니다.

2021-02-07 08:05 UTC, PandaHun commented on 5week/calculator/src/main/java/Service/CalStart.java
> +            if (str.length % 2 == 0) {
검증을 먼저 해주면 할당을 생략할 수 있지않을까요?

2021-02-07 08:05 UTC, PandaHun commented on 5week/calculator/src/main/java/Service/CalStart.java
> +                first.setNum(new Cal().cal(first, second, operator));
쉽게 이해가 가지않는 코드라고 생각합니다.

2021-02-07 08:05 UTC, PandaHun commented on 5week/calculator/src/main/java/Service/CalStart.java
> +            new View(first.getNum());
매번 새로운 View 객체를 생성하는 것보다
한번 생성한 View 객체가 동작을 하는 방향은 어떨까요?

2021-02-07 08:05 UTC, PandaHun commented on 5week/calculator/src/main/java/Service/Cal.java
> +    public BigDecimal cal(Number first, Number second, Operator operator) {
메소드명을 함축시키지 마세요

2021-02-07 08:05 UTC, PandaHun commented on 5week/calculator/document/calculator.md
> +    * 입력 값
입력 값이 결국 앞의 3가지 아닌가요?

2021-02-14 23:52 UTC, PandaHun requested changes
생각해주세요~

2021-02-14 23:52 UTC, PandaHun commented on 5week/calculator/src/main/java/Domain/Number.java
> +    private static BigDecimal zero = new BigDecimal(0);
값이 바뀔 경우가 있을까요?
없다면 final로 선언하고 `ZERO`라고 선언해주면 어떨까요??

2021-02-14 23:52 UTC, PandaHun commented on 5week/calculator/src/main/java/Service/View.java
> +    public static void View(BigDecimal result) {
생성자가 아니라 메소드 아닌가요?

2021-02-15 23:33 UTC, PandaHun approved these changes

2021-02-15 23:33 UTC, PandaHun commented on 5week/calculator/src/main/java/Domain/Number.java
> +    private static final BigDecimal zero = new BigDecimal(0);
final 변수는 상수로 `ZERO`로 선언해주는게 좋습니다

2021-02-18 08:15 UTC, PandaHun requested changes

2021-02-18 08:15 UTC, PandaHun commented on 5week/calculator/src/main/java/Domain/Number.java
> +    private static final BigDecimal zero = new BigDecimal(0); //잉? 바꿔놨는디
```suggestion
    private static final BigDecimal ZERO = new BigDecimal(0); //잉? 바꿔놨는디
```

2021-02-21 06:55 UTC, DongLee99 commented on 5week/calculator/src/main/java/Domain/Number.java
> +    private static final BigDecimal zero = new BigDecimal(0); //잉? 바꿔놨는디
대문자로 바꾸라는건가요?

2021-02-21 11:07 UTC, PandaHun approved these changes

2021-02-21 12:39 UTC, closed without merging