[5주차] ejy
Learning-Now/2021-Java-Study pull request #34
Opened 2021-02-05 13:46 UTC by jeongyuneo

2021-02-07 01:57 UTC, PandaHun requested changes
거의다 된 것 같은데 사용하지 않는 클래스 삭제, 좀 더 좋은 네이밍이 개선되면 좋을 것 같습니다

2021-02-07 01:57 UTC, PandaHun commented on 5주차/프로그래밍과제1-1/src/main/java/service/Calculator.java
> +            Number number = new Number(exceptionCatcher.catchWrongNumber(formula[i + 1]));
number라는 네이밍이 와닿지 않는것 같습니다
```suggestion
            Number nextArgument = new Number(exceptionCatcher.catchWrongNumber(formula[i + 1]));
```
같은 네이밍도 있습니다.

2021-02-07 01:57 UTC, PandaHun commented on 5주차/프로그래밍과제1-1/src/main/java/service/Calculator.java
> +            int tmp = operators.operateFormula(result, operator, number);
`calculateResult`라는 네이밍 제안해봅니다

2021-02-07 01:57 UTC, PandaHun commented on 5주차/프로그래밍과제1-1/src/main/java/domain/Operators.java
> +        if (operator.getValue().equals("+")) {
`else-if`는 지양합니다

2021-02-07 01:57 UTC, PandaHun commented on 5주차/프로그래밍과제1-1/src/main/java/oper.java
> +public class oper {
안쓰는 클래스는 삭제해주세요

2021-02-07 10:39 UTC, jeongyuneo commented on 5주차/프로그래밍과제1-1/src/main/java/oper.java
> +public class oper {
수정 완료

2021-02-07 10:41 UTC, jeongyuneo commented on 5주차/프로그래밍과제1-1/src/main/java/domain/Operators.java
> +        if (operator.getValue().equals("+")) {
수정 완료

2021-02-07 10:48 UTC, jeongyuneo commented on 5주차/프로그래밍과제1-1/src/main/java/service/Calculator.java
> +            Number number = new Number(exceptionCatcher.catchWrongNumber(formula[i + 1]));
수정 완료

2021-02-07 10:48 UTC, jeongyuneo commented on 5주차/프로그래밍과제1-1/src/main/java/service/Calculator.java
> +            int tmp = operators.operateFormula(result, operator, number);
수정 완료

2021-02-07 10:56 UTC, Livenow14 reviewed
구현할 기능목록 어디에..?!

2021-02-07 10:56 UTC, Livenow14 commented on 5주차/자바 기초.md
> +
int a = Scanner.nextInt();
switch(a/10)
이게 안된다는 말씀이신가요?!

2021-02-07 10:56 UTC, Livenow14 commented on 5주차/자바 기초.md
> +
예제 한번 만들어봐도 좋을거같아요 :)

2021-02-07 10:56 UTC, Livenow14 commented on 5주차/프로그래밍과제1-1/src/main/java/domain/Number.java
> +}
set가 없어도 되지 않을까요?!

2021-02-08 04:12 UTC, jeongyuneo commented on 5주차/프로그래밍과제1-1/src/main/java/domain/Number.java
> +}
수정 완료

2021-02-08 04:31 UTC, PandaHun approved these changes

2021-02-08 04:56 UTC, jeongyuneo commented on 5주차/자바 기초.md
> +
```java
int a = 5;
if (a <= 5) { // 가능
    System.out.println("5 이하");
}
switch (a) {
    case a <= 5: // 불가능
        System.out.println("5 이하");
}
```

2021-02-08 05:03 UTC, jeongyuneo commented on 5주차/자바 기초.md
> +
수정 완료

2021-02-21 12:39 UTC, closed without merging