[6주차] ejy
Learning-Now/2021-Java-Study pull request #39
Opened 2021-02-23 08:01 UTC by jeongyuneo

2021-02-27 01:04 UTC, PandaHun requested changes
접근제한자, 다수의 요청을 처리할 때 생길 수 있는 문제에 대해서 생각해보고 적용해주세요

2021-02-27 01:04 UTC, PandaHun commented on 6주차/프로그래밍 과제/src/main/java/domain/Number.java
> +    final int value;
변수의 접근제한은 어떻게 되는거죠?

2021-02-27 01:04 UTC, PandaHun commented on 6주차/프로그래밍 과제/src/main/java/service/CalculatorStarter.java
> +public class CalculatorStarter {
아는 것이 있다고 했는데 없는 것 같아요

2021-02-27 01:04 UTC, PandaHun commented on 6주차/프로그래밍 과제/src/main/java/service/CalculatorStarter.java
> +        calculator.calculateFormula(scannerInputView.getFormular());
계산기 반환이라는 동작을 수행하고 있나요?

2021-02-27 01:04 UTC, PandaHun commented on 6주차/프로그래밍 과제/src/main/java/service/Calculator.java
> +    private final int FIRSTARGUMENT = 0;
상수명을 짓는 방법에 대해서 찾아보면 좋을 것 같아요

2021-02-27 01:04 UTC, PandaHun commented on 6주차/프로그래밍 과제/src/main/java/service/Calculator.java
> +        FormulaSplitter formulaSplitter = new FormulaSplitter();
계산기가 무수히 많아진다면 해당 클래스는 계속해서 새로 생성되겠네요?

2021-02-27 01:04 UTC, PandaHun commented on 6주차/프로그래밍 과제/src/main/java/service/FormulaSplitter.java
> +    public int splitNumber(String formularArguement) {
메소드 명과 동작이 매치가 안되는 것 같습니다

2021-02-27 04:22 UTC, jeongyuneo commented on 6주차/프로그래밍 과제/src/main/java/service/Calculator.java
> +    private final int FIRSTARGUMENT = 0;
수정 완료

2021-02-27 10:53 UTC, jeongyuneo commented on 6주차/프로그래밍 과제/src/main/java/domain/Number.java
> +    final int value;
수정 완료

2021-02-27 11:11 UTC, jeongyuneo commented on 6주차/프로그래밍 과제/src/main/java/service/CalculatorStarter.java
> +public class CalculatorStarter {
수정 완료

2021-02-27 11:11 UTC, jeongyuneo commented on 6주차/프로그래밍 과제/src/main/java/service/CalculatorStarter.java
> +        calculator.calculateFormula(scannerInputView.getFormular());
수정 완료

2021-02-27 11:15 UTC, jeongyuneo commented on 6주차/프로그래밍 과제/src/main/java/service/FormulaSplitter.java
> +    public int splitNumber(String formularArguement) {
수정 완료

2021-02-27 16:30 UTC, jeongyuneo commented on 6주차/프로그래밍 과제/src/main/java/service/Calculator.java
> +        FormulaSplitter formulaSplitter = new FormulaSplitter();
수정 완료

2021-02-28 02:09 UTC, PandaHun requested changes
궁금한 사항들에 대해 남겨뒀습니다

2021-02-28 02:09 UTC, PandaHun commented on 6주차/프로그래밍 과제/src/main/java/domain/Number.java
> +        if (value == 0) {
`0`이라는 숫자가 특별한 의미를 갖고 있다면
그 의미를 노출시켜 줄 때 코드가 더 이해하기 좋을 것 같습니다.

2021-02-28 02:09 UTC, PandaHun commented on 6주차/프로그래밍 과제/src/main/java/domain/Operators.java
> +        if (operator.value.equals("/") && !number2.validate()) {
`validate`를 해당 조건이 참인 경우로 바꾸면 `!`을 안붙여도 될 것 같아요

2021-02-28 02:09 UTC, PandaHun commented on 6주차/프로그래밍 과제/src/main/java/service/Calculator.java
> +    private static final int FIRST_ARGUMENT = 0;
전역 변수여야 할 이유가 있을까요?

2021-03-02 02:26 UTC, jeongyuneo commented on 6주차/프로그래밍 과제/src/main/java/domain/Number.java
> +        if (value == 0) {
수정 완료

2021-03-02 02:26 UTC, jeongyuneo commented on 6주차/프로그래밍 과제/src/main/java/domain/Operators.java
> +        if (operator.value.equals("/") && !number2.validate()) {
수정 완료

2021-03-02 04:25 UTC, jeongyuneo commented on 6주차/프로그래밍 과제/src/main/java/service/Calculator.java
> +    private static final int FIRST_ARGUMENT = 0;
'메소드 10줄 이내'라는 때문에 전역 변수로 뺐습니다.

2021-03-02 14:25 UTC, PandaHun approved these changes

2021-03-27 12:32 UTC, closed without merging