[6주차] ysy
Learning-Now/2021-Java-Study pull request #42
Opened 2021-02-28 08:13 UTC by dustndus8

2021-02-28 15:04 UTC, PandaHun requested changes
1. .idea 폴더는 gitignore에 추가해주세요
2. 궁금한것들과 생각해볼 것들 코멘트 달았습니다.
3. 이번주 과제인 Enum 부분이 생략된 것 같은데 참고부탁드려요

2021-02-28 15:04 UTC, PandaHun commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +    InputCheck ic = new InputCheck();
1. 외부에 노출되어 있는 이유가 있을까요?
2. 인수인계 받을 사람 혹은 협업하는 사람이 변수명을 한번에 이해할 수 있을까요?

2021-02-28 15:04 UTC, PandaHun commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +}
주석은 삭제해주세요

2021-02-28 15:04 UTC, PandaHun commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +        inputString = in.getNextLine();
선언과 할당을 나눈 이유가 있나요?

2021-02-28 15:04 UTC, PandaHun commented on 6주차과제/프로그래밍과제1/java/util/SplitString.java
> +        return strArray;
변수 `strArray`가 꼭 필요할까요?

2021-02-28 15:04 UTC, PandaHun commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +        System.out.println("합계 : " + c.calculate(strResultArray));
자기 자신의 메소드를 호출 할 수 있다면 객체를 추가 생성할 필요가 없을 것 같은데
해당 방법을 생각해보세요

2021-02-28 15:04 UTC, PandaHun commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +    public int calculate(String[] sps) {
메소드를 선언할 때는 `sps` 사용할 때는 `strResultArray`라서 쉽게 이해되지 않습니다~

2021-02-28 15:04 UTC, PandaHun commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +        return sum;
위 코드대로 동작한다면 처음부터 끝까지 총 4번의 연산을 거치게 되는데
n * 4 의 복잡도를 가지는 것을 개선할 수 있을까요?

2021-02-28 15:04 UTC, PandaHun commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +        for (int i = 0; i < sps.length - 2; i += 2) {
`0`번과 그 이후 `2` 만큼 증가한 수가 무엇을 의미하는 걸까요?
보통 매직넘버라고 하는데 의미를 부여해 주면 이해하기가 쉽겠죠?

2021-03-01 10:22 UTC, dustndus8 commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +}
주석 삭제 완료했습니다! 그런데 혹시 주석을 삭제하는 이유를 여쭤봐도 될까요??

2021-03-01 10:25 UTC, dustndus8 commented on 6주차과제/프로그래밍과제1/java/util/SplitString.java
> +        return strArray;
strArray 삭제하고 바로 return 할 수 있도록 수정했습니다!

2021-03-01 10:30 UTC, dustndus8 commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +        System.out.println("합계 : " + c.calculate(strResultArray));
객체 생성하는 코드 삭제해서 메소드 호출하는 것으로 수정했습니다!

2021-03-01 10:36 UTC, dustndus8 commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +    InputCheck ic = new InputCheck();
1. 기존에 썼던 calculate 메소드가 길어 여러 메소드로 분리하는 과정에서 해당 코드를 위로 보냈는데, 외부로부터 보호 하는 것을 놓쳤습니다! private를 붙여 수정했습니다!
2. op같은 경우에는 이해할 수 있을 것 같은데, 그 외에 것은 이해하기 힘들 것 같습니다. 지금까지는 객체의 변수 이름을 네이밍할 때, 클래스의 이름을 축약한 것으로 많이 써왔는데, ToInt와 InputCheck의 경우는 어떻게 네이밍을 할 지 잘 모르겠습니다!

2021-03-01 10:51 UTC, dustndus8 commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +        for (int i = 0; i < sps.length - 2; i += 2) {
매직넘버 수정 완료했습니다!

2021-03-01 11:37 UTC, PandaHun commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +    InputCheck ic = new InputCheck();
클래스의 이름을 명사형으로 지어준다면 조금 더 이해하기 편할 것같아요
`IntegerParser`, `InputChecker` 등 다양한 방법이 있겠죠??

2021-03-01 11:38 UTC, PandaHun commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +}
주석없이도 이해할 수 있는 코드를 작성하는게 더 좋은 코드를 작성했다고 할 수 있어요
주석이 필요하다면 코드 만으로 설명할 수 없는 코드라는 거겠죠?

2021-03-01 11:39 UTC, PandaHun requested changes

2021-03-01 11:39 UTC, PandaHun commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +    private static final int NUMBER = 2;
더 좋은 네이밍을 생각해봤으면 좋겠어요!

2021-03-01 11:46 UTC, dustndus8 commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +}
넵! 이해했습니다 감사합니다!

2021-03-01 11:47 UTC, dustndus8 commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +    InputCheck ic = new InputCheck();
넵! 그러면 클래스 이름을 명사형으로 수정하고, 객체 이름을 ip, ic로 하는 것은 괜찮을까요?

2021-03-01 12:03 UTC, PandaHun commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +    InputCheck ic = new InputCheck();
클래스이름도 수정하면서 같은 이름으로 변수명을 주면 더 좋지않을까요?
만약에 `InputChecker`라면 `inputChecker`라는 식으로요

2021-03-02 04:25 UTC, dustndus8 commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +    InputCheck ic = new InputCheck();
수정완료했습니다!

2021-03-02 14:25 UTC, PandaHun approved these changes

2021-03-03 04:02 UTC, dustndus8 commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +    public int calculate(String[] sps) {
변수명 변경했습니다!

2021-03-03 04:48 UTC, dustndus8 commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +        return sum;
calculate 메소드에서 if 문으로 구분해서 개선하면 메소드의 길이가 10줄을 넘어버려 calculateByOperator 함수를 만들어 수정했습니다!

2021-03-03 05:03 UTC, dustndus8 commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +    private static final int NUMBER = 2;
수정했습니다! 그런데 수정한 네이밍 또한 좋은 네이밍인지 잘 모르겠습니다
상수 명명 규칙을 찾아봤는데, 모두 대문자와ㅏ _을 이용해 한다고 되어있는데, MAKE와 같은 동사형태도 써도 되는 지 궁금합니다!

2021-03-03 05:11 UTC, dustndus8 commented on 6주차과제/프로그래밍과제1/java/util/Calculator.java
> +        inputString = in.getNextLine();
처음 이 프로젝트를 코딩할 때, 하드코딩??을 하지 말라고 하셔서 if문이나 for문 등의 안에 있는 선언을 위로 보냈었는데, 지금 다시 보니 이부분은 선언과 할당을 동시에 해도 되는 것 같습니다..!! 수정했습니다!!

2021-03-03 13:27 UTC, PandaHun approved these changes

2021-03-03 13:28 UTC, PandaHun commented
docs라는 커밋 메시지를 feat 혹은 refactor 등으로 바꾸는 걸 고려해주세요!
docs는 문서에 대한 커밋 메시지에요

2021-03-15 01:16 UTC, PandaHun approved these changes

2021-03-27 12:32 UTC, closed without merging