[7주차] ejy
Learning-Now/2021-Java-Study pull request #46
Opened 2021-03-12 12:26 UTC by jeongyuneo

2021-03-13 03:28 UTC, PandaHun requested changes
전반적으로 괜찮으나
생각해볼 부분이 있어서 피드백드립니다

2021-03-13 03:28 UTC, PandaHun commented on 7주차/프로그래밍과제1/src/main/java/service/Calculator.java
> +    private Calculator() {
생성자가 상수보다 먼저 나오고 있습니다
확인부탁드려요

2021-03-13 03:28 UTC, PandaHun commented on 7주차/프로그래밍과제1/src/main/java/service/Calculator.java
> +            String stringResult = Integer.toString(operator.calculate(calculatedResult.getValue(), nextArgument.getValue()));
파싱의 단계가 많이 들어가서 이해하기 쉽진 않은데
개선의 여지가 있을 것같습니다

2021-03-13 04:09 UTC, jeongyuneo commented on 7주차/프로그래밍과제1/src/main/java/service/Calculator.java
> +    private Calculator() {
수정 완료

2021-03-13 04:42 UTC, jeongyuneo commented on 7주차/프로그래밍과제1/src/main/java/service/Calculator.java
> +            String stringResult = Integer.toString(operator.calculate(calculatedResult.getValue(), nextArgument.getValue()));
수정 완료

2021-03-14 07:27 UTC, PandaHun approved these changes

2021-03-27 12:32 UTC, closed without merging